brick_labels = {"Sensor": [
        "Active_Power_Sensor",
        "Air_Flow_Sensor",
        "Air_Temperature_Sensor",
        "Angle_Sensor",
        "Average_Zone_Air_Temperature_Sensor",
        "Chilled_Water_Differential_Temperature_Sensor",
        "Chilled_Water_Return_Temperature_Sensor",
        "Chilled_Water_Supply_Flow_Sensor",
        "Chilled_Water_Supply_Temperature_Sensor",
        "Cooling_Demand_Sensor",
        "Current_Sensor",
        "Damper_Position_Sensor",
        "Demand_Sensor",
        "Differential_Pressure_Sensor",
        "Differential_Supply_Return_Water_Temperature_Sensor",
        "Discharge_Air_Dewpoint_Sensor",
        "Discharge_Air_Temperature_Sensor",
        "Discharge_Water_Temperature_Sensor",
        "Duration_Sensor",
        "Electrical_Power_Sensor",
        "Energy_Usage_Sensor",
        "Filter_Differential_Pressure_Sensor",
        "Flow_Sensor",
        "Frequency_Sensor",
        "Heating_Demand_Sensor",
        "Hot_Water_Flow_Sensor",
        "Hot_Water_Return_Temperature_Sensor",
        "Hot_Water_Supply_Temperature_Sensor",
        "Load_Current_Sensor",
        "Outside_Air_CO2_Sensor",
        "Outside_Air_Enthalpy_Sensor",
        "Outside_Air_Humidity_Sensor",
        "Outside_Air_Temperature_Sensor",
        "Peak_Power_Demand_Sensor",
        "Position_Sensor",
        "Power_Sensor",
        "Pressure_Sensor",
        "Rain_Sensor",
        "Reactive_Power_Sensor",
        "Return_Air_Temperature_Sensor",
        "Return_Water_Temperature_Sensor",
        "Solar_Radiance_Sensor",
        "Static_Pressure_Sensor",
        "Supply_Air_Humidity_Sensor",
        "Supply_Air_Static_Pressure_Sensor",
        "Supply_Air_Temperature_Sensor",
        "Temperature_Sensor",
        "Thermal_Power_Sensor",
        "Usage_Sensor",
        "Valve_Position_Sensor",
        "Voltage_Sensor",
        "Warmest_Zone_Air_Temperature_Sensor",
        "Water_Flow_Sensor",
        "Water_Temperature_Sensor",
        "Wind_Direction_Sensor",
        "Wind_Speed_Sensor",
        "Zone_Air_Dewpoint_Sensor",
        "Zone_Air_Humidity_Sensor",
        "Zone_Air_Temperature_Sensor",
    ],
    "Setpoint": [
        "Air_Flow_Setpoint",
        "Air_Temperature_Setpoint",
        "Cooling_Demand_Setpoint",
        "Cooling_Supply_Air_Temperature_Deadband_Setpoint",
        "Cooling_Temperature_Setpoint",
        "Damper_Position_Setpoint",
        "Dew_Point_Setpoint",
        "Differential_Pressure_Setpoint",
        "Discharge_Air_Temperature_Setpoint",
        "Flow_Setpoint",
        "Heating_Demand_Setpoint",
        "Heating_Supply_Air_Temperature_Deadband_Setpoint",
        "Heating_Temperature_Setpoint",
        "Humidity_Setpoint",
        "Low_Outside_Air_Temperature_Enable_Setpoint",
        "Max_Air_Temperature_Setpoint",
        "Min_Air_Temperature_Setpoint",
        "Outside_Air_Lockout_Temperature_Setpoint",
        "Outside_Air_Temperature_Setpoint",
        "Reset_Setpoint",
        "Room_Air_Temperature_Setpoint",
        "Speed_Setpoint",
        "Static_Pressure_Setpoint",
        "Supply_Air_Static_Pressure_Setpoint",
        "Supply_Air_Temperature_Setpoint",
        "Temperature_Setpoint",
        "Time_Setpoint",
        "Water_Temperature_Setpoint",
        "Zone_Air_Humidity_Setpoint",
    ],
    "Demand_Sensor": [
        "Cooling_Demand_Sensor",
        "Heating_Demand_Sensor",
        "Peak_Power_Demand_Sensor",
    ],
    "Flow_Sensor": [
        "Air_Flow_Sensor",
        "Chilled_Water_Supply_Flow_Sensor",
        "Hot_Water_Flow_Sensor",
        "Water_Flow_Sensor",
    ],
    "Flow_Setpoint": ["Air_Flow_Setpoint"],
    "Humidity_Setpoint": ["Zone_Air_Humidity_Setpoint"],
    "Power_Sensor": [
        "Active_Power_Sensor",
        "Electrical_Power_Sensor",
        "Reactive_Power_Sensor",
        "Thermal_Power_Sensor",
    ],
    "Pressure_Sensor": [
        "Differential_Pressure_Sensor",
        "Filter_Differential_Pressure_Sensor",
        "Static_Pressure_Sensor",
        "Supply_Air_Static_Pressure_Sensor",
    ],
    "Position_Sensor": [
        "Damper_Position_Sensor",
        "Valve_Position_Sensor",
    ],
    "Temperature_Sensor": [
        "Air_Temperature_Sensor",
        "Average_Zone_Air_Temperature_Sensor",
        "Chilled_Water_Differential_Temperature_Sensor",
        "Chilled_Water_Return_Temperature_Sensor",
        "Chilled_Water_Supply_Temperature_Sensor",
        "Differential_Supply_Return_Water_Temperature_Sensor",
        "Discharge_Air_Temperature_Sensor",
        "Discharge_Water_Temperature_Sensor",
        "Hot_Water_Return_Temperature_Sensor",
        "Hot_Water_Supply_Temperature_Sensor",
        "Outside_Air_Temperature_Sensor",
        "Return_Air_Temperature_Sensor",
        "Return_Water_Temperature_Sensor",
        "Supply_Air_Temperature_Sensor",
        "Warmest_Zone_Air_Temperature_Sensor",
        "Water_Temperature_Sensor",
        "Zone_Air_Temperature_Sensor",
    ],
    "Temperature_Setpoint": [
        "Air_Temperature_Setpoint",
        "Cooling_Temperature_Setpoint",
        "Discharge_Air_Temperature_Setpoint",
        "Heating_Temperature_Setpoint",
        "Max_Air_Temperature_Setpoint",
        "Min_Air_Temperature_Setpoint",
        "Outside_Air_Lockout_Temperature_Setpoint",
        "Outside_Air_Temperature_Setpoint",
        "Room_Air_Temperature_Setpoint",
        "Supply_Air_Temperature_Setpoint",
        "Water_Temperature_Setpoint",
    ],
    "Usage_Sensor": ["Energy_Usage_Sensor"],
    "Air_Temperature_Sensor": [
        "Average_Zone_Air_Temperature_Sensor",
        "Discharge_Air_Temperature_Sensor",
        "Outside_Air_Temperature_Sensor",
        "Return_Air_Temperature_Sensor",
        "Supply_Air_Temperature_Sensor",
        "Warmest_Zone_Air_Temperature_Sensor",
        "Zone_Air_Temperature_Sensor",
    ],
    "Air_Temperature_Setpoint": [
        "Discharge_Air_Temperature_Setpoint",
        "Max_Air_Temperature_Setpoint",
        "Min_Air_Temperature_Setpoint",
        "Outside_Air_Temperature_Setpoint",
        "Room_Air_Temperature_Setpoint",
        "Supply_Air_Temperature_Setpoint",
    ],
    "Differential_Pressure_Sensor": [
        "Filter_Differential_Pressure_Sensor",
    ],
    "Static_Pressure_Sensor": [
        "Supply_Air_Static_Pressure_Sensor",
    ],
    "Static_Pressure_Setpoint": [
        "Supply_Air_Static_Pressure_Setpoint",
    ],
    "Water_Temperature_Sensor": [
        "Differential_Supply_Return_Water_Temperature_Sensor",
        "Discharge_Water_Temperature_Sensor",
        "Return_Water_Temperature_Sensor",
    ],
}

unique_labels = (set(value for sublist in brick_labels.values() for value in sublist).union(set(brick_labels.keys()))
                 .union({'Sensor', 'Alarm', 'Command', 'Parameter', 'Setpoint', 'Status'}))
