y_columns = ['Discharge_Water_Temperature_Sensor', 'Air_Temperature_Setpoint',
       'Temperature_Setpoint', 'Energy_Usage_Sensor', 'Status',
       'Voltage_Sensor', 'Demand_Sensor',
       'Hot_Water_Supply_Temperature_Sensor', 'Solar_Radiance_Sensor',
       'Active_Power_Sensor', 'Outside_Air_CO2_Sensor',
       'Wind_Direction_Sensor', 'Hot_Water_Return_Temperature_Sensor',
       'Air_Temperature_Sensor', 'Thermal_Power_Sensor',
       'Average_Zone_Air_Temperature_Sensor', 'Supply_Air_Temperature_Sensor',
       'Chilled_Water_Supply_Flow_Sensor',
       'Chilled_Water_Return_Temperature_Sensor', 'Parameter',
       'Speed_Setpoint', 'Load_Current_Sensor',
       'Discharge_Air_Temperature_Setpoint', 'Humidity_Setpoint', 'Alarm',
       'Water_Flow_Sensor', 'Rain_Sensor', 'Outside_Air_Humidity_Sensor',
       'Water_Temperature_Setpoint', 'Time_Setpoint', 'Frequency_Sensor',
       'Heating_Demand_Sensor', 'Cooling_Demand_Setpoint',
       'Chilled_Water_Differential_Temperature_Sensor',
       'Room_Air_Temperature_Setpoint', 'Outside_Air_Temperature_Setpoint',
       'Cooling_Temperature_Setpoint', 'Position_Sensor', 'Setpoint',
       'Duration_Sensor', 'Air_Flow_Sensor',
       'Filter_Differential_Pressure_Sensor', 'Differential_Pressure_Setpoint',
       'Temperature_Sensor', 'Flow_Sensor', 'Water_Temperature_Sensor',
       'Peak_Power_Demand_Sensor', 'Wind_Speed_Sensor', 'Power_Sensor',
       'Discharge_Air_Temperature_Sensor', 'Outside_Air_Temperature_Sensor',
       'Outside_Air_Enthalpy_Sensor',
       'Chilled_Water_Supply_Temperature_Sensor', 'Hot_Water_Flow_Sensor',
       'Static_Pressure_Setpoint', 'Supply_Air_Static_Pressure_Setpoint',
       'Supply_Air_Static_Pressure_Sensor', 'Heating_Demand_Setpoint',
       'Angle_Sensor', 'Zone_Air_Humidity_Setpoint', 'Static_Pressure_Sensor',
       'Damper_Position_Setpoint', 'Air_Flow_Setpoint', 'Command',
       'Return_Air_Temperature_Sensor', 'Differential_Pressure_Sensor',
       'Return_Water_Temperature_Sensor', 'Dew_Point_Setpoint',
       'Cooling_Supply_Air_Temperature_Deadband_Setpoint',
       'Zone_Air_Temperature_Sensor', 'Reset_Setpoint',
       'Low_Outside_Air_Temperature_Enable_Setpoint',
       'Max_Air_Temperature_Setpoint', 'Sensor', 'Supply_Air_Humidity_Sensor',
       'Cooling_Demand_Sensor', 'Electrical_Power_Sensor',
       'Reactive_Power_Sensor', 'Flow_Setpoint', 'Valve_Position_Sensor',
       'Usage_Sensor', 'Supply_Air_Temperature_Setpoint',
       'Discharge_Air_Dewpoint_Sensor',
       'Outside_Air_Lockout_Temperature_Setpoint', 'Damper_Position_Sensor',
       'Heating_Temperature_Setpoint', 'Min_Air_Temperature_Setpoint',
       'Pressure_Sensor', 'Heating_Supply_Air_Temperature_Deadband_Setpoint',
       'Differential_Supply_Return_Water_Temperature_Sensor',
       'Zone_Air_Dewpoint_Sensor', 'Zone_Air_Humidity_Sensor',
       'Warmest_Zone_Air_Temperature_Sensor', 'Current_Sensor']

top_feats = ['autocorrelation', 'sampling_rate', 'event_density', 'trigger_ratio',
       'state_length', 'largest_state', 'dominant_state',
       '25th Percentile of Time Diffs (seconds)',
       '75th Percentile of Time Diffs (seconds)',
       'Median Absolute Deviation (MAD) of Time Diffs (seconds)',
       'Minimum Time Difference (seconds)', 'permutation_entropy',
       'sample_entropy', 'rms', 'energy', 'event_density_5T',
       'trigger_ratio_5T', 'state_length_5T', 'largest_state_5T',
       'dominant_state_5T', 'permutation_entropy_5T', 'rms_5T',
       'spectral_entropy_1H', 'event_density_1H', 'trigger_ratio_1H',
       'state_length_1H', 'largest_state_1H', 'dominant_state_1H',
       'permutation_entropy_1H', 'rms_1H', 'smallest_state_1D',
       'largest_state_1D', 'dominant_state_1D', 'rms_1D', 'event_density_1W',
       'trigger_ratio_1W', 'smallest_state_1W', 'largest_state_1W',
       'dominant_state_1W', 'rms_1W']